# Generated by Django 2.1.7 on 2019-06-06 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0008_instructor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя', max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(help_text='Введите имя', max_length=50, verbose_name='Имя')),
                ('side', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.Course')),
            ],
        ),
    ]
