# Generated by Django 2.1.7 on 2019-06-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(help_text='Загрузите фотографию', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='surname',
            field=models.CharField(help_text='Введите фамилию', max_length=50, verbose_name='Фамилия'),
        ),
    ]
