# Generated by Django 2.1.7 on 2019-06-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0009_auto_20190606_2040'),
        ('students', '0002_auto_20190606_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Введите дату в формате ГГГГ-ММ-ДД', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='students',
            name='description',
            field=models.TextField(blank=True, help_text='В данное поле вводится краткая биография и основные черты личности', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='students',
            name='lider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.Instructor', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(help_text='Загрузите фотографию', null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='students',
            name='side',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.Course', verbose_name='Политические взгляды'),
        ),
    ]
