# Generated by Django 2.1.7 on 2019-06-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190606_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='surname',
            field=models.CharField(help_text='Введите фамилию', max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
