# Generated by Django 2.1.7 on 2019-06-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20190610_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='side',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.Course', verbose_name='Программа подготовки'),
        ),
    ]
