# Generated by Django 2.1.7 on 2019-06-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20190611_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], max_length=1, null=True, verbose_name='Пол'),
        ),
    ]
