# Generated by Django 2.1.7 on 2019-06-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('course', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=510)),
                ('subscribe', models.BooleanField()),
                ('comment', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_apply', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
