# Generated by Django 2.1.7 on 2019-06-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactapply',
            name='course',
            field=models.CharField(choices=[('s', 'Сальса casino'), ('b', 'Бачата')], default='Бачата', max_length=20, verbose_name='Курс'),
        ),
    ]
