# Generated by Django 2.1.7 on 2019-05-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='emaill',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='course',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(help_text='This is name', max_length=255, verbose_name='Instructor name'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='surname',
            field=models.CharField(max_length=225),
        ),
    ]
