# Generated by Django 2.1.7 on 2019-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_auto_20190530_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
