# Generated by Django 2.1.7 on 2019-06-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_auto_20190601_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='course',
        ),
        migrations.AddField(
            model_name='instructor',
            name='course',
            field=models.ManyToManyField(to='instructors.Course'),
        ),
    ]
