# Generated by Django 2.1.7 on 2019-06-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0008_instructor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='simbols',
            field=models.ImageField(help_text='Загрузите фотографию', null=True, upload_to='', verbose_name='Флаг'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(help_text='Загрузите фотографию', null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
