# Generated by Django 2.1.7 on 2019-06-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0013_instructor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
